const random = {
	name: 'Surprise me',
	backgroundImg: '',
	length: 'wide',
};
const categories = [
	{
		name: 'generation',
		backgroundImg: '',
		subcategories: [
			{ name: 'i', backgroundImg: '' },
			{ name: 'ii', backgroundImg: '' },
			{ name: 'iii', backgroundImg: '' },
			{ name: 'iv', backgroundImg: '' },
			{ name: 'v', backgroundImg: '' },
			{ name: 'vi', backgroundImg: '' },
			{ name: 'vii', backgroundImg: '' },
			{ name: 'viii', backgroundImg: '' },
		],
	},
	{
		name: 'type',
		backgroundImg: '',
		subcategories: [
			{ name: 'normal', backgroundImg: '' },
			{ name: 'fire', backgroundImg: '' },
			{ name: 'water', backgroundImg: '' },
			{ name: 'electric', backgroundImg: '' },
			{ name: 'grass', backgroundImg: '' },
			{ name: 'ice', backgroundImg: '' },
			{ name: 'fighting', backgroundImg: '' },
			{ name: 'poison', backgroundImg: '' },
			{ name: 'ground', backgroundImg: '' },
			{ name: 'flying', backgroundImg: '' },
			{ name: 'psychic', backgroundImg: '' },
			{ name: 'bug', backgroundImg: '' },
			{ name: 'rock', backgroundImg: '' },
			{ name: 'ghost', backgroundImg: '' },
			{ name: 'dragon', backgroundImg: '' },
			{ name: 'dark', backgroundImg: '' },
			{ name: 'steel', backgroundImg: '' },
			{ name: 'fairy', backgroundImg: '' },
		],
	},
	{
		name: 'shape',
		backgroundImg: '',
		subcategories: [
			{ name: 'ball', backgroundImg: '' },
			{ name: 'squiggle', backgroundImg: '' },
			{ name: 'fish', backgroundImg: '' },
			{ name: 'arms', backgroundImg: '' },
			{ name: 'blob', backgroundImg: '' },
			{ name: 'upright', backgroundImg: '' },
			{ name: 'legs', backgroundImg: '' },
			{ name: 'quadruped', backgroundImg: '' },
			{ name: 'wings', backgroundImg: '' },
			{ name: 'tentacles', backgroundImg: '' },
			{ name: 'heads', backgroundImg: '' },
			{ name: 'humanoid', backgroundImg: '' },
			{ name: 'bug-wings', backgroundImg: '' },
			{ name: 'armor', backgroundImg: '' },
		],
	},
	{
		name: 'color',
		backgroundImg: '',
		subcategories: [
			{ name: 'black', backgroundImg: '' },
			{ name: 'blue', backgroundImg: '' },
			{ name: 'brown', backgroundImg: '' },
			{ name: 'gray', backgroundImg: '' },
			{ name: 'green', backgroundImg: '' },
			{ name: 'pink', backgroundImg: '' },
			{ name: 'purple', backgroundImg: '' },
			{ name: 'red', backgroundImg: '' },
			{ name: 'white', backgroundImg: '' },
			{ name: 'yellow', backgroundImg: '' },
		],
	},
];

export {
  random,
  categories
}